---
# Configure activemq

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ activemq_services_enable }}"
  when: activemq_enable_service
