---
# Install activemq packages

- name: unwanted packages are removed
  package:
    name: "{{ activemq_packages_remove }}"
    state: absent
  become: true
  when: activemq_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ activemq_packages_repos }}"
    state: "{{ activemq_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ activemq_packages_prereq }}"
    state: "{{ activemq_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ activemq_packages_install }}"
    state: "{{ activemq_packages_state }}"
  become: true
